name: gsoilflow
description: Gestion ravitaillement gasoil pour engins de chantier industriel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Base de données locale
  sqflite: ^2.3.3
  path: ^1.9.0

  # Caméra
  image_picker: ^1.1.2

  # PDF
  pdf: ^3.11.1
  printing: ^5.13.1
  path_provider: ^2.1.3

  # Partage fichiers
  share_plus: ^9.0.0

  # Excel import
  excel: ^4.0.3
  file_picker: ^8.1.2

  # Crypto (SHA-256)
  crypto: ^3.0.3

  # UI
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
